---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pizza-fe-secret
  namespace: pizza
spec:
  encryptedData:
    BACKEND_HOST: AgBdIVhp7T/UcfQkb3pszSs4g+ltWi+asGYRcAZNStb8KBEfv4G3ssD/ekaq1C+GUqBaCNG91g6+XkZv6Gr9NAAFpZ+mr2Yr5ejZCbiNCtZA4URo9VimaGMcIfY4aPiMzmAsRthCd560la6ZWaCKiLhCRJ73JSqlofZvyxy4zU5MissNxJFaAfB+TqY/2i904OVaKspjWM0uGCqs4Wz186uCfuk21nj5Xv6igO/ymUG+Tf440eZh1ahRmHGvx/wwstScP3zYDhPwxLhZwgCbpILOMq37Me5D29aw0glsef6QfssrxUKk2fbgMBuuhRdSH9LyawGM6/6blHqruzDN4W6a9nC9jgOpjEwHUP9B8fNS+7Vqd5XbVBfQCn7aJg9So+iIPyHR0ls5e1awO75sdv31/3wpk2cfe9bJIlz5ytT0iRl7lzL3+EUjuHU2qfJHB7lMplrX8zO23pJNA6TqA1qYpe11gwRUqP1r9UyqvHxDgXvPuOzlscSRUOAfbX3LRv5TRCNj5NrKCwrX68cHfo5DUlNUUqH8DPDVABpB1OZOurEwNgB2oGM4aV8rRchaeM0EGMGNRHH4c+V4u+p1MSZV8hRhFbVmQ7hepcLQp2RwPyqWEh/x8LLoO4ptlZYxs/fGznuDiCrespkyu3e4yufGnF/d8Qa6j0eaxRGlbwGZf30W9VHk3j8+j8Yeuv/tcOBlWLAy0jq/nw==
    BACKEND_PORT: AgCKttaXBsMkP9IGdu+nTr9WtygUMTtXjNxrF7RuMDUt0sgLbjV2OYThQB9KYHwONd+ElUPgByse8Q7/bhcYeUXgUgnwxVSK3adIGeal/ZyVBvIOoDiLcpK7X6HP6zHgcHzrT9F5Th1mlxpP6VlUrG2FVqq9ZCfXdZ/ItO4DiAOSzKxPv/YvZEZx9Qo/BDLoScUozCY2CfAGRqK6fCflAN3TJJTtHXxM9LZW9nOrVEKrCGhUE9NVBGPiSerqblGkrI3gHFCXrQ3iXTHE3mxBatPZpf/HNAJuwXWp9bXCj3v0PI2QP2DLCAtLqner7ZQ15rbt7V/8Tv2i7vKqkKCp1gCAtKaO+jpphLlvFGRNLGiJFxhOlA2g48X9+tdJd3DR6EfmbSv/B1f1VzikEGc0eG1MBsWYWEzxjbudCspbcGVnulGhBI0lnjvFpHjBk6tX/ouZYYaJ0nh571IXUHlzjFK+M+KhOulQwPtgXZqOar2cp3HR3g9Wb4ro86DSF9DzTzPv/MHO3osf6upF9ep8NjsT/yjQhm8nY+lYrxwLVB5v6krbPRwdNM5IGKqQygL/RWtakep0SlR7UTaTglJVFTMx/h08HJ9Ve3tpgVjz4i/h8f4ThMqwG+edJpCUYy+blklHujKS2mOzeiv0nw6HJj7TMqB0S5Iktl5eXMtBgO/vQDmDhNRDAq9gbnF8z/KjMQXPGR2L
  template:
    metadata:
      creationTimestamp: null
      name: pizza-fe-secret
      namespace: pizza
